/// <reference types="vite/client" />

/**
 * Environment variable type declarations
 *
 * Provides type safety for environment variables in SvelteKit.
 * Uses $env/* imports which are auto-generated by SvelteKit.
 */

declare module '$env/static/private' {
  /**
   * Password for production authentication
   * Required in production when PUBLIC_AUTH_MODE is not set to 'open'
   */
  export const AUTH_PASSWORD: string;
}

declare module '$env/static/public' {
  /**
   * Explicitly set authentication mode
   * - 'password': Require password authentication
   * - 'open': No password required (development mode)
   * - '' or undefined: Auto-detect based on import.meta.env.PROD
   */
  export const PUBLIC_AUTH_MODE: 'password' | 'open' | '';
}
